repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: black reactor/
        language: system
        always_run: true
        pass_filenames: false
      - id: mypy
        name: mypy
        entry: mypy reactor/ --check-untyped-defs --explicit-package-bases --warn-unreachable # --warn-return-any
        language: system
        always_run: true
        pass_filenames: false
      - id: tests
        name: subset of tests
        entry: pytest reactor/test/test.py
        language: system
        always_run: true
        pass_filenames: false
      - id: pylint
        name: pylint
        entry: pylint reactor/
        language: system
        always_run: true
        pass_filenames: false
